title: Peter Nowak
description: My Personal Blog
author: Peter Nowak
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/pjnowak1213
about: Leadership, Agile Coach, sDevOps, Architect

disqus_shortname: pjnowak1213
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
